#!/usr/bin/env bash
# Builds Glasswork's Linux installer: one file that, opened, installs the app for whoever
# opened it, or updates an installation already there. See linux/installer/installer.c.
#
#   linux/packaging/build_installer.sh             build the release app, then the installer
#   linux/packaging/build_installer.sh --no-build  package the release build already there
#
# Writes build/linux/installer/Glasswork-Setup-<version>-<arch>. Open it from Files, or run
# it. The version comes from pubspec.yaml, so bump it there for every release: that is what
# the installer compares to tell an update from a reinstall.
#
# For tests: --bundle DIR packages DIR instead of the release build, --version V labels it,
# and --output FILE says where the installer goes.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../.." && pwd)"
app_id="dev.mrhyperion.glasswork"

bundle="$root/build/linux/x64/release/bundle"
build=1
version=""
output=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-build) build=0 ;;
    --bundle) bundle="$2"; build=0; shift ;;
    --version) version="$2"; shift ;;
    --output) output="$2"; shift ;;
    *) echo "Unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

if [[ -z "$version" ]]; then
  version="$(sed -n 's/^version:[[:space:]]*//p' "$root/pubspec.yaml" | head -n 1)"
fi
if [[ -z "$output" ]]; then
  output="$root/build/linux/installer/Glasswork-Setup-${version%%+*}-$(uname -m)"
fi

for tool in cc pkg-config tar gzip python3; do
  if ! command -v "$tool" >/dev/null; then
    echo "Building the installer needs $tool." >&2
    exit 1
  fi
done
if ! pkg-config --exists gtk+-3.0; then
  echo "Building the installer needs GTK 3's development files (gtk3 on Arch, libgtk-3-dev on Debian)." >&2
  exit 1
fi

if [[ "$build" == 1 ]]; then
  # The Supabase project to sync with, where this clone has one. Without it the app builds
  # fine and keeps everything on the device: see backend.example.json and the README.
  # GLASSWORK_NO_BACKEND=1 leaves it out deliberately: that is how the binaries on the
  # releases page are built, since they are nobody's project to sync with but their own.
  backend=()
  if [[ -n "${GLASSWORK_NO_BACKEND:-}" ]]; then
    echo "GLASSWORK_NO_BACKEND: building an app that keeps everything on this device." >&2
  elif [[ -f "$root/backend.json" ]]; then
    backend=(--dart-define-from-file=backend.json)
  else
    echo "No backend.json: building an app that keeps everything on this device." >&2
  fi
  (cd "$root" && flutter build linux --release "${backend[@]}")
fi
if [[ ! -x "$bundle/glasswork" ]]; then
  echo "There is no app to package at $bundle." >&2
  echo "Build one first:  flutter build linux --release" >&2
  exit 1
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# What the installer unpacks: the app with its version, and its desktop entry and icons.
payload="$work/payload"
mkdir -p "$payload/app"
cp -a "$bundle/." "$payload/app/"
printf '%s\n' "$version" > "$payload/app/VERSION"
install -D -m 644 "$here/$app_id.desktop" "$payload/share/applications/$app_id.desktop"
for icon in "$here"/icons/*/apps/"$app_id".png; do
  size="$(basename "$(dirname "$(dirname "$icon")")")"
  install -D -m 644 "$icon" "$payload/share/icons/hicolor/$size/apps/$app_id.png"
done
tar -C "$payload" -czf "$work/payload.tar.gz" .

# The icon the installer's own window shows, compiled in.
python3 - "$here/icons/256x256/apps/$app_id.png" "$work/icon.h" <<'PY'
import sys

data = open(sys.argv[1], "rb").read()
with open(sys.argv[2], "w") as out:
    out.write("/* Generated by build_installer.sh from the 256px app icon. */\n")
    out.write("static const unsigned char kIcon[] = {\n")
    for i in range(0, len(data), 20):
        out.write("  " + ", ".join(str(b) for b in data[i:i + 20]) + ",\n")
    out.write("};\n")
    out.write(f"static const unsigned int kIconLength = {len(data)};\n")
PY

# shellcheck disable=SC2046  # pkg-config's flags are meant to split.
cc -O2 -Wall -Wextra -o "$work/installer" \
  -DGW_VERSION="\"$version\"" -DGW_HAVE_ICON -I"$work" \
  "$root/linux/installer/installer.c" \
  $(pkg-config --cflags --libs gtk+-3.0)

# The app goes after the program, then its length and a marker, which is how the program
# finds it.
python3 - "$work/payload.tar.gz" "$work/trailer" <<'PY'
import os
import struct
import sys

with open(sys.argv[2], "wb") as out:
    out.write(struct.pack("<Q", os.path.getsize(sys.argv[1])) + b"GWSETUP1")
PY

mkdir -p "$(dirname "$output")"
cat "$work/installer" "$work/payload.tar.gz" "$work/trailer" > "$output.partial"
chmod 755 "$output.partial"
mv -f "$output.partial" "$output"

echo "Built $output ($(du -h "$output" | cut -f1))"
